### ISSUE TITLE
Module instead of package

### ISSUE THREAD

**Issue by basnijholt** [erdewit/nest_asyncio#1]
I see there is only one file on the package. I think you should make an installable module out of it :)

**Comment by erdewit** [comment]
That would be a good idea but setuptools seems to insist on a package directory so I don't know how.

**Comment by basnijholt** [comment]
See this for an example https://github.com/basnijholt/adaptive-tools/blob/master/setup.py.

**Comment by erdewit** [comment]
Thx for the info, I've just applied it. The magic word was py_modules.
