### ISSUE TITLE
Include LICENSE in released package

### ISSUE THREAD

**Issue by diego-plan9** [erdewit/nest_asyncio#13]
First of all, thanks for making `nest_asyncio` available - it covers a very handy use case! I was wondering if it would be possible to make a new release that includes the `LICENSE` file along with the rest of the files, in order to facilitate proper attribution.

**Comment by erdewit** [comment]
The LICENSE file is now added to the distribution.

**Comment by diego-plan9** [comment]
Thanks a lot @erdewit !

**Comment by diego-plan9** [comment]
Actually, on a closer look: would it be possible to have the `LICENSE` file included in the `.tar.gz`, and not only in the `.whl`?
