### ISSUE TITLE
Not compatible with Python 3.6

### ISSUE THREAD

**Issue by Parakoopa** [erdewit/nest_asyncio#24]
Hi, just letting you know, that commit 3a2c8a2be3482a2d0a8561eda89e87bd096e21f0 broke Python 3.6 (and probably 3.5) compatibility, because `run_forever` is no longer patched. 

1.2.3 seems to work perfectly for this version though, so I don't think a fix is neccesary, you might want to update the README though.

Thanks for this package!

**Comment by erdewit** [comment]
The patched ``run_forever`` method from 1.2.3 has been re-added again.
