### ISSUE TITLE
Python 3.6 still gives same error 

### ISSUE THREAD

**Issue by Nicholas7435** [erdewit/nest_asyncio#27]
![image](https://user-images.githubusercontent.com/10407878/83935492-0638d480-a788-11ea-8d4c-953b37d3f0cb.png)

**Comment by unkcpz** [comment]
hi @Nicholas7435 , I think I encounter the similar problem as you, could you check with my fork to see if that will solve your problem?

**Comment by Nicholas7435** [comment]
Hello! I believe that I have properly install your fork, but I am still getting the same error. I appreciate your time.

![image](https://user-images.githubusercontent.com/10407878/83974056-70509700-a8b8-11ea-8a5e-419b69e2a0de.png)

![image](https://user-images.githubusercontent.com/10407878/83974069-89594800-a8b8-11ea-9660-19e6575d952e.png)

**Comment by erdewit** [comment]
This should be fixed with #24.
