### ISSUE TITLE
Task not executing

### ISSUE THREAD

**Issue by davidbrochart** [erdewit/nest_asyncio#3]
Say you have a file `foo.py`:

```python
import asyncio

async def foo():
    print('foo')
    await asyncio.sleep(0)
    print('done')

loop = asyncio.get_event_loop()
task = asyncio.ensure_future(foo())
loop.run_until_complete(task)
```

And a Notebook with this cell:

```python
import nest_asyncio
nest_asyncio.apply()

import foo
```

Executing the cell just hangs, `foo()` is not executed.

**Comment by erdewit** [comment]
It can be made to work by directly running the coroutine, without ensure_future:

```python
coro = foo()
loop.run_until_complete(coro)
```

I'll have to look deeper if the combination of ensure_future and run_until_complete of the same task can be made to work.

**Comment by davidbrochart** [comment]
The problem is that I can't modify this code. Here it is juste a minimal example to reproduce the bug.

**Comment by davidbrochart** [comment]
Actually I have a slightly more complex case where it still hangs:

```python
import asyncio

async def foo():
    print('foo')
    await asyncio.sleep(0)
    print('done')

loop = asyncio.get_event_loop()
task = asyncio.ensure_future(foo())
finished, unfinished = loop.run_until_complete(asyncio.wait([task], return_when=asyncio.ALL_COMPLETED))
```

**Comment by erdewit** [comment]
The code is overhauled in a pretty major way to fix this bug and several other lingering issues.

Thank you for your bug reports, they have been added as Travis test cases.

**Comment by davidbrochart** [comment]
Everything works fine for me now, thanks a lot for your support!
