### ISSUE TITLE
timeout 

### ISSUE THREAD

**Issue by simongarisch** [erdewit/nest_asyncio#33]
Hi there.

I was wondering where the [choice of 10 came from](https://github.com/erdewit/nest_asyncio/blob/43467067b87b20325c4cbaaf78af8eff16ecf847/nest_asyncio.py#L110) for the timeout variable in nest_asyncio.py. 
```python
        timeout = 0 if ready or self._stopping \
            else min(max(0, scheduled[0]._when - now), 10) if scheduled \
            else None
```

To get my code to work I had to increment this slightly.

Thanks,
Simon.

**Comment by erdewit** [comment]
The select timeout is increased to one day, which is what asyncio uses as default.

I'm puzzled how this value can have any effect on running code, would have thought it doesn't matter.
