### ISSUE TITLE
Running this with serial_asyncio fails to close the COM ports

### ISSUE THREAD

**Issue by scottbgoldblatt** [erdewit/nest_asyncio#4]
The first time the following serial application runs, it succeeds.  However, the second time it is run it fails:

SerialException: could not open port 'com3': PermissionError(13, 'Access is denied.', None, 5)
---------------------
import asyncio
import serial_asyncio
import nest_asyncio

async def main(loop):
    reader, _ = await serial_asyncio.open_serial_connection(url='com3', baudrate=115200)
    print('Reader created')
    _, writer = await serial_asyncio.open_serial_connection(url='com4', baudrate=115200)
    print('Writer created')
    messages = [b'foo\n', b'bar\n', b'baz\n', b'qux\n']
    sent = send(writer, messages)
    received = recv(reader)
    
    await asyncio.wait([sent, received])
    
    
    print('finished! main')
    

async def send(w, msgs):
    for msg in msgs:
        w.write(msg)
        print(f'sent: {msg.decode().rstrip()}')
        await asyncio.sleep(0.5)
    w.write(b'DONE\n')
    print('Done sending')

async def recv(r):
    while True:
        msg = await r.readuntil(b'\n')
        if msg.rstrip() == b'DONE':
            print('Done receiving')
            break
        print(f'received: {msg.rstrip().decode()}')
    

nest_asyncio.apply()

loop = asyncio.get_event_loop()
loop.run_until_complete(main(loop))
print('finished! loop')

**Comment by erdewit** [comment]
Probably you'll need to .close() the read/write streams and add some pause until really closed. On python 3.7 the [wait_closed](https://docs.python.org/3/library/asyncio-stream.html#asyncio.StreamWriter.wait_closed) coroutine can be awaited. If this is not the problem feel free to reopen the bug.
