### ISSUE TITLE
Can't patch loop of type <class 'uvloop.Loop'>

### ISSUE THREAD

**Issue by BobCashStory** [erdewit/nest_asyncio#49]
I'm using sanic as server who use uvloop instead of asyncio.

nest_asyncio doesn't allow me to apply on uvloop asyncio.

Does it's planned on future release to support it ?

**Comment by erdewit** [comment]
uvloop is a C-extension and is not possible to patch.

**Comment by xappppp** [comment]
getting the same issue when i'm setting up the fastapi and trying to add IB to the app, not sure if this context can give any viable workaround
