### ISSUE TITLE
RuntimeError: There is no current event loop in thread "worker 0"

### ISSUE THREAD

**Issue by afarntrog** [erdewit/nest_asyncio#52]
Hi,

Thank you, @erdewit,  for building this library.

When using the `nest_asyncio.apply()` patch with the [Bottle web framework](https://bottlepy.org/docs/dev/) and running the  paste server I encounter the following error: `RuntimeError: There is no current event loop in thread 'worker 0'`

Here is the **complete** code to reproduce issue:
```
from bottle import route, run, template
import nest_asyncio

@route('/')
def index(name='jack'):
    nest_asyncio.apply()
    return template('<b>Hello {{name}}</b>!', name=name)

run(server='paste', host='localhost', port=8080, debug=True)
```
If you don't have these libraries installed then run:
`pip install bottle` 
`pip install nest-asyncio`
`pip install paste`

---
Here is the **complete** exception:
```
Error: 500 Internal Server Error
Sorry, the requested URL 'http://localhost:8080/' caused an error:

Internal Server Error
Exception: RuntimeError("There is no current event loop in thread 'worker 0'.")

Traceback:
Traceback (most recent call last):
  File "c:\Users\env\lib\site-packages\bottle.py", line 868, in _handle
    return route.call(**args)
  File "c:\Users\env\lib\site-packages\bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "c:\Users\mybottle.py", line 5, in index
    nest_asyncio.apply()
  File "c:\Users\env\lib\site-packages\nest_asyncio.py", line 12, in apply
    loop = loop or asyncio.get_event_loop()
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'worker 0'.
```
---
This `threading.current_thread() is threading.main_thread()` here [cpython/Lib/asyncio/events.py](https://github.com/python/cpython/blob/bb3e0c240bc60fe08d332ff5955d54197f79751c/Lib/asyncio/events.py#L652)  is evaluating to False which is causing the exception to be raised.
We can update `.apply()` to set a new event loop for this thread if it is missing? https://github.com/erdewit/nest_asyncio/blob/fb7d35e4874923c3417912c8f7e9ec14c4a5ae6a/nest_asyncio.py#L12

**Comment by erdewit** [comment]
There are several options. The best one is to use a fully asyncio-based application server, such as aiohtttp, sanic, quart, fastapi, etc. and to use fully async code.

Another option is to use the native bottle server instead of the paste server; It is single-threaded and will not cause issues (but will be blocking other concurrent requests).

A third option is to keep using the multi threaded paste server and create an event loop for each thread:
```python
    try:
        asyncio.get_event_loop()
    except RuntimeError:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        nest_asyncio.apply(loop)
```

**Comment by afarntrog** [comment]
Thanks @erdewit .
