### ISSUE TITLE
Exception handlers do not seem to work after apply().

### ISSUE THREAD

**Issue by taimurrabuske** [erdewit/nest_asyncio#6]
In my application, after I apply the patch, the exception handler that I set is not used for exceptions. Is this the expected behavior?

Cheers.

**Comment by erdewit** [comment]
loop.set_exception_handler() should work, provided it uses the right loop. Can you give a minimal example were it doesn't work?

**Comment by taimurrabuske** [comment]
You're right.
I just found out that it is due to some incompatibility with another module (promp_toolkit), which also patches the asyncio event loop. I will investigate further and give some feedback later.
