### ISSUE TITLE
nest_asyncio.apply() to check for asyncio.AbstractEventLoop

### ISSUE THREAD

**Issue by sylim2357** [erdewit/nest_asyncio#60]
https://github.com/erdewit/nest_asyncio/blob/960fccf8fa089d0cdbf813e0c9474cf055bfa489/nest_asyncio.py#L13

Suggesting to use asyncio.AbstractEventLoop instead of asyncio.BaseEventLoop
- can support wider range of loops incl. uvloop

**Comment by erdewit** [comment]
The patching relies on some implementation details that are specific to the asyncio BaseEventLoop. It will unfortunately not work with uvloop or other non-asyncio loops (that I know of).
