### ISSUE TITLE
1.5.2 and 1.5.3 broke some current_task detection

### ISSUE THREAD

**Issue by euri10** [erdewit/nest_asyncio#64]
hello

I have an issue in my whole test suite, seems different from #62 and not fixed in 1.5.3

I pinpointed it to a library using `sniffio` at `library = sniffio.current_async_library()` ( it should return asyncio in my case)

while debugging it, it seems in 1.5.1 detects fine that `current_task() is not None` line 82 while in 1.5.2 and 3 it doesn't
the relevant part of `sniffio` if interesting:
https://github.com/python-trio/sniffio/blob/949b2591da374bf20c77cad79f66920389094d6f/sniffio/_impl.py#L75-L95

I bisect the regression is introduced by b69926a1b20d19aaa5de1e73581aa8bac177dd4a

**Comment by erdewit** [comment]
Thank you for bisecting. I have reverted the relevant part (fix for #57) and this is released as v1.5.4.

**Comment by euri10** [comment]
thanks for the quick fix @erdewit
