### ISSUE TITLE
1.5.1-1.5.4 is breaking vaex due to #61 

### ISSUE THREAD

**Issue by maartenbreddels** [erdewit/nest_asyncio#65]
since #61 out CI breaks (tested locally), but I'm not sure why yet, it seems some tasks don't get executed.

I know this is not (yet) a helpful issue, but in case other people are finding this version range a breaking change, maybe is will help debugging this together.

**Comment by forna** [comment]
For me the last version of nest_asyncio working is the 1.5.1. 
1.5.2 produces an error message: ValueError: Can't patch loop of type <class 'NoneType'>
1.5.3 and .1.5.4 do not execute the async code and I get just timeouts.

**Comment by erdewit** [comment]
There is not much to go on from these reports, but I suspect it has to do with multithreading.
The new v1.5.5 release might offer an improvement in this regard

**Comment by forna** [comment]
You are right, my application is multithreaded.
I can confirm v.1.5.5 fixes the issue, thank you so much.
