### ISSUE TITLE
Request stuck in ProcessPoolExecutor

### ISSUE THREAD

**Issue by ObjatieGroba** [erdewit/nest_asyncio#68]
asyncio.exceptions.TimeoutError on first request inside ProcessPollExecutor ~~with DNS lookup only.~~

```
Traceback (most recent call last):
  File "/home/mineev/projects/ng-ci-scripts/nestkek.py", line 14, in download
    async with session.get(url, timeout=1) as resp:
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/client.py", line 619, in _request
    break
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

Yes, it can be illegal to use async inside sync function at ProcessPoolExecutor, I suppose, but that's never stopped us before. (:

Timeout will NOT be raised if comment `download` in `handler`.

All next requests in the same process of pool will not produce exception.

Request never ends if timeout is None.

How can I fix it?

Simple example:

```
import asyncio
import traceback

import aiohttp
import nest_asyncio
from concurrent.futures import ProcessPoolExecutor

nest_asyncio.apply()


async def download(url='http://github.com'):
    try:
        async with aiohttp.ClientSession() as session:
            async with session.get(url, timeout=1) as resp:
                print(resp.status)
                return await resp.text()
    except Exception as e:
        print(e)
        print(traceback.format_exc())


def sync_task():
    loop = asyncio.get_event_loop()
    return loop.run_until_complete(download())


pool = ProcessPoolExecutor(max_workers=1)


async def handler():
    # Comment next line will fix TimeOut Exception
    await download("http://google.com")
    loop = asyncio.get_event_loop()
    res = await loop.run_in_executor(pool, sync_task)
    print(len(res) if res else None)


def main():
    loop = asyncio.get_event_loop()
    loop.run_until_complete(handler())  # Timeout
    loop.run_until_complete(handler())  # no timeout


if __name__ == "__main__":
    main()

```

**Comment by ObjatieGroba** [comment]
Requests without DNS lookup inside `sync_task` do not raise Exceptions in some cases, but I could not find a pattern...

**Comment by ObjatieGroba** [comment]
Removing pool (request in the same thread) fix Exception too, but this is not an option

**Comment by ObjatieGroba** [comment]
Fixed with replace `loop = asyncio.get_event_loop()` -> `loop = asyncio.new_event_loop()` in `sync_task`
Or with `asyncio.run(download())`

Seems it is bug. The bug is not the first download call exception, the bug is other call success)

**Comment by erdewit** [comment]
You're using a process pool with forked processes:
https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods
This can lead to very weird behaviour, certainly when sockets, threads or event loops are forked over to the new child processes. Spawning the processes (instead of forking) will fix the issue, something like

```python
if __name__ == "__main__":
    mp.set_start_method('spawn')
    pool = ProcessPoolExecutor(max_workers=1)
    main()
```
