### ISSUE TITLE
AttributeError: 'Loop' object has no attribute '_check_closed'

### ISSUE THREAD

**Issue by paduel** [erdewit/nest_asyncio#7]
Hi Ewald.

I fallen in love with ib_insync several months ago. Now I look for a solution to nested loops, I find this amazing package, and it's yours too. Great Ewald !

I'm trying to use with aiogram and my own async code. But I get this error. I'm using  Python 3.7.2.

Could you help me?  Thanks for your brilliant work.

```
...
  File "/home/argante/anaconda2/Proyectos 8/beagledwx/dwx.py", line 51, in data_request
    data = list_of_dict_to_dict(loop.run_until_complete(future))
  File "/home/argante/anaconda2/envs/python372/lib/python3.7/site-packages/nest_asyncio.py", line 53, in run_until_complete
    self._check_closed()
AttributeError: 'Loop' object has no attribute '_check_closed'
```

**Comment by erdewit** [comment]
Hi Paduel, glad you like my wares. Not sure what sort of project you're using this with, but if the ``_check_closed`` method is not part of the loop then it's not a standard asyncio loop and can't be patched. 

I've added a check that throws a more informative exception.
