### ISSUE TITLE
nest_asyncio.apply not working unless entire asyncio package is imported

### ISSUE THREAD

**Issue by sha2fiddy** [erdewit/nest_asyncio#78]
I have not had any success using nest_asyncio.apply without importing the entire asyncio package:
`import asyncio`
`import nest_asyncio`

This import practice is often undesirable, and sometimes prohibited by linters.  Is there any way to apply nest_asyncio with only certain asyncio objects imported?
`from asyncio import create_task, gather, run`
`from nest_asyncio import apply as nest`

The apply method executes, but running the async code results in the same issue that I am using nest_asyncio for in the first place:
`RuntimeError Traceback (most recent call last)`

Apologies if this already possible or written about, I could not find any mention in the docs or stack exchange.  Thank you

**Comment by erdewit** [comment]
> This import practice is often undesirable, and sometimes prohibited by linters. Is there any way to apply nest_asyncio with only certain asyncio objects imported?

There are some methods patched directly on the asyncio module, so it has to be imported entirely.
