### ISSUE TITLE
Using with Quamash

### ISSUE THREAD

**Issue by danieljfarrell** [erdewit/nest_asyncio#8]
I use this project a lot recently with Jupyter notebooks for testing async code, thanks! Hope it’s OK to leave a question here?

In your readme it says this probably will not work with quamash events loops, I was wondering if you could let me know more about that, such as what’s the main difficult?

I am using Quamash for a desktop QT application and I’m coming up against the classic problem of interoperability with legacy code that I cannot change.  I need to call an ‘async def’ function and waiting for it to complete inside a ‘def’ function. 

Do you think nest_asyncio could help? Or do you think it’s not worth it because it may introduce really hard to track down bugs?

**Comment by erdewit** [comment]
Check out [ib_insync.util.useQt()](https://rawgit.com/erdewit/ib_insync/master/docs/html/_modules/ib_insync/util.html#useQt).

It's made to be used with nest_asyncio.

**Comment by danieljfarrell** [comment]
Thanks! 

Does this replace Quamash? I’m not too sure the use case for this. How would I use this in my QT app?

**Comment by erdewit** [comment]
Yes, it replaces quamash. Just call useQt() and start the asyncio loop.

There's a demo here: https://github.com/erdewit/ib_insync/blob/master/examples/qt_ticker_table.py

**Comment by danieljfarrell** [comment]
Perfect! Will try that.
